### ISSUE TITLE
By Year clarification.

### ISSUE THREAD

**Issue by jasonjac2** [AliDehbansiahkarbon/PascalPantheon#1]
Does year, mean the year the the repo was created?
Do you create this manually or in code?

**Comment by AliDehbansiahkarbon** [comment]
# Hi, 
## This list is created by querying the GitHub API and shows the year of the repository's first upload(initial commit).

## The API's documentation can be found [here.](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-public-repositories)

## A simple UI for this API can be found [here](https://kamranahmed.info/githunt).

**Comment by jasonjac2** [comment]
Thanks for that.  A very useful dashboard.  Clearly I could get my finger out and learn it, but I would love to make a suggestion.
Different views:
- Votes in a period (so 2024 just has them ordered by *'s in 2024 regardless of when they were created)
- Votes in a moving windows period to show the rise and fall. So like the above but 2024 = votes in 2019 - 2024.
Thanks for the resource.

**Comment by AliDehbansiahkarbon** [comment]
Good Idea but you know, this is not a real website, it's actually made by GitHub pages and it's static somehow.
Something like what is in your mind takes more time and investigation.
Maybe in the future but I don't have time for it now, unfortunately,
If you have time please contribute, you are very welcome.
